import React from 'react';
import type { Country, Theme } from '../types.ts';
import { formatDate } from '../utils.ts';
import Icon from './Icon.tsx';

interface CountryProfilePageProps { theme: Theme; country: Country | null; onNavigate: (view: any) => void; }

const Field: React.FC<{ label: string; value: React.ReactNode }> = ({ label, value }) => <div className="border-b border-[#efede7] py-3 last:border-0"><dt className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#96948c]">{label}</dt><dd className="mt-1.5 text-sm font-medium text-[#343430]">{value || '—'}</dd></div>;

const CountryProfilePage: React.FC<CountryProfilePageProps> = ({ country, onNavigate }) => {
  if (!country) return <div className="surface-card grid min-h-64 place-items-center p-8 text-center"><div><p className="text-sm font-semibold">No country selected</p><button onClick={() => onNavigate('countries')} className="mt-4 text-xs font-semibold underline underline-offset-4">Return to countries</button></div></div>;
  const levels = [...(country.adminLevelNames || [])].sort((a, b) => a.level - b.level);

  return <div className="space-y-6">
    <section className="surface-card flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between md:p-6"><div className="flex items-center gap-4"><div className="h-14 w-20 overflow-hidden rounded-xl border border-[#e3e1d9] bg-[#fafaf7]"><img src={`https://flagcdn.com/w160/${country.countryCode.toLowerCase()}.png`} alt={`Flag of ${country.name}`} className="h-full w-full object-cover" /></div><div><div className="flex items-center gap-2"><h2 className="text-2xl font-semibold tracking-[-0.035em]">{country.name}</h2><span className="rounded-full bg-[#fff4c7] px-2 py-1 text-[10px] font-semibold text-[#6e5700]">{country.countryCode}</span></div><p className="mt-1 text-xs text-[#88867f]">{country.continent}</p></div></div><button onClick={() => onNavigate('countries')} className="button-secondary self-start sm:self-auto"><Icon name="chevron-left" className="h-4 w-4" /> Back to countries</button></section>

    <div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]">
      <div className="space-y-6"><section className="surface-card p-5"><h3 className="text-sm font-semibold">Country details</h3><dl className="mt-4"><Field label="Official name" value={country.name} /><Field label="ISO code" value={country.countryCode} /><Field label="Calling code" value={country.phoneCode} /><Field label="Currency" value={`${country.currency} (${country.currencyCode})`} /><Field label="VAT rate" value={`${country.vat}%`} /></dl></section><section className="surface-card p-5"><h3 className="text-sm font-semibold">Record information</h3><dl className="mt-4"><Field label="Administrative levels" value={country.numberOfAdminLevels || 0} /><Field label="Electoral levels" value={country.numberOfElectoralLevels || 0} /><Field label="Created by" value={country.createdBy} /><Field label="Last updated" value={formatDate(country.updatedAt || new Date().toISOString())} /></dl></section></div>
      <div className="space-y-6"><section className="surface-card p-5 md:p-6"><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold">Administrative structure</h3><p className="mt-1 text-xs text-[#88867f]">Configured hierarchy from highest to lowest level.</p></div><span className="rounded-full bg-[#f4f3ee] px-2.5 py-1 text-[10px] font-semibold text-[#77766f]">{levels.length} levels</span></div>{levels.length ? <div className="mt-6 space-y-2">{levels.map((level, index) => <div key={level.level} className="flex items-center gap-3 rounded-xl border border-[#ebe9e2] bg-[#fafaf7] p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#fff4c7] text-[10px] font-bold text-[#6e5700]">{String(index + 1).padStart(2, '0')}</span><span className="text-sm font-medium">{level.name}</span>{index < levels.length - 1 && <Icon name="chevron-down" className="ml-auto h-4 w-4 text-[#aaa79e]" />}</div>)}</div> : <div className="mt-6 rounded-xl bg-[#fafaf7] p-6 text-center text-xs text-[#88867f]">No hierarchy definition has been added.</div>}</section><section className="surface-card overflow-hidden"><div className="border-b border-[#ebe9e2] p-5"><h3 className="text-sm font-semibold">Registered administrative areas</h3><p className="mt-1 text-xs text-[#88867f]">{country.adminLevels.length.toLocaleString()} connected records</p></div><div className="max-h-[420px] overflow-auto">{country.adminLevels.length ? <table className="w-full text-left text-xs"><thead className="sticky top-0 bg-[#fafaf7]"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Level</th><th className="px-4 py-3">Type</th></tr></thead><tbody className="divide-y divide-[#efede7]">{country.adminLevels.map(area => <tr key={area.id}><td className="px-4 py-3 font-medium">{area.name}</td><td className="px-4 py-3 text-[#77766f]">{area.level}</td><td className="px-4 py-3 text-[#77766f]">{levels.find(item => item.level === area.level)?.name || `Level ${area.level}`}</td></tr>)}</tbody></table> : <p className="p-8 text-center text-xs text-[#88867f]">No administrative areas have been added.</p>}</div></section></div>
    </div>
  </div>;
};

export default CountryProfilePage;
