import React from 'react';
import type { Country, Theme } from '../types.ts';
import { formatDate } from '../utils.ts';
import Icon from './Icon.tsx';

interface CountryProfilePageProps { theme: Theme; country: Country | null; onNavigate: (view: any) => void; }
const Field: React.FC<{ label: string; value: React.ReactNode; dark: boolean }> = ({ label, value, dark }) => <div className={`border-b py-3 last:border-0 ${dark ? 'border-slate-700' : 'border-slate-200'}`}><dt className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">{label}</dt><dd className={`mt-1.5 text-sm font-medium ${dark ? 'text-slate-200' : 'text-slate-800'}`}>{value || '—'}</dd></div>;

const CountryProfilePage: React.FC<CountryProfilePageProps> = ({ theme, country, onNavigate }) => {
  const dark = theme === 'dark';
  const panel = dark ? 'border-slate-700 bg-slate-900' : 'border-slate-200 bg-white';
  if (!country) return <div className={`grid min-h-64 place-items-center rounded-lg border p-8 text-center shadow-sm ${panel}`}><div><p className="text-sm font-semibold">No country selected</p><button onClick={() => onNavigate('countries')} className="mt-4 text-xs font-semibold text-yellow-500 hover:underline">Return to countries</button></div></div>;
  const levels = [...(country.adminLevelNames || [])].sort((a, b) => a.level - b.level);
  return <div className="space-y-6">
    <section className={`flex flex-col gap-5 rounded-lg border p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between md:p-6 ${panel}`}><div className="flex items-center gap-4"><div className="h-14 w-20 overflow-hidden rounded-md border border-slate-600 bg-slate-100"><img src={`https://flagcdn.com/w160/${country.countryCode.toLowerCase()}.png`} alt={`Flag of ${country.name}`} className="h-full w-full object-cover" /></div><div><div className="flex items-center gap-2"><h2 className="text-2xl font-bold">{country.name}</h2><span className="rounded-full bg-yellow-100 px-2 py-1 text-[10px] font-semibold text-yellow-800">{country.countryCode}</span></div><p className="mt-1 text-xs text-slate-500">{country.continent}</p></div></div><button onClick={() => onNavigate('countries')} className={`flex items-center gap-2 self-start rounded-md border px-4 py-2 text-sm font-semibold sm:self-auto ${dark ? 'border-slate-600 hover:bg-slate-800' : 'border-slate-300 hover:bg-slate-50'}`}><Icon name="chevron-left" className="h-4 w-4" /> Back to countries</button></section>
    <div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="space-y-6"><section className={`rounded-lg border p-5 shadow-sm ${panel}`}><h3 className="font-bold">Country details</h3><dl className="mt-4"><Field dark={dark} label="Official name" value={country.name} /><Field dark={dark} label="ISO code" value={country.countryCode} /><Field dark={dark} label="Calling code" value={country.phoneCode} /><Field dark={dark} label="Currency" value={`${country.currency} (${country.currencyCode})`} /><Field dark={dark} label="VAT rate" value={`${country.vat}%`} /></dl></section><section className={`rounded-lg border p-5 shadow-sm ${panel}`}><h3 className="font-bold">Record information</h3><dl className="mt-4"><Field dark={dark} label="Administrative levels" value={country.numberOfAdminLevels || 0} /><Field dark={dark} label="Electoral levels" value={country.numberOfElectoralLevels || 0} /><Field dark={dark} label="Created by" value={country.createdBy} /><Field dark={dark} label="Last updated" value={formatDate(country.updatedAt || new Date().toISOString())} /></dl></section></div>
      <div className="space-y-6"><section className={`rounded-lg border p-5 shadow-sm ${panel}`}><div className="flex justify-between"><div><h3 className="font-bold">Administrative structure</h3><p className="mt-1 text-xs text-slate-500">Configured from highest to lowest level.</p></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs font-semibold ${dark ? 'bg-slate-800 text-slate-300' : 'bg-slate-100 text-slate-600'}`}>{levels.length} levels</span></div>{levels.length ? <div className="mt-5 space-y-2">{levels.map((level, index) => <div key={level.level} className={`flex items-center gap-3 rounded-md border p-3 ${dark ? 'border-slate-700 bg-slate-800/50' : 'border-slate-200 bg-slate-50'}`}><span className="grid h-8 w-8 place-items-center rounded bg-yellow-500 text-xs font-black text-slate-900">{String(index + 1).padStart(2, '0')}</span><span className="text-sm font-medium">{level.name}</span></div>)}</div> : <p className="mt-5 rounded-md bg-slate-800/30 p-6 text-center text-xs text-slate-500">No hierarchy definition has been added.</p>}</section><section className={`overflow-hidden rounded-lg border shadow-sm ${panel}`}><div className={`border-b p-5 ${dark ? 'border-slate-700' : 'border-slate-200'}`}><h3 className="font-bold">Registered administrative areas</h3><p className="mt-1 text-xs text-slate-500">{country.adminLevels.length.toLocaleString()} connected records</p></div><div className="max-h-[420px] overflow-auto">{country.adminLevels.length ? <table className="w-full text-left text-xs"><thead className={dark ? 'bg-slate-800' : 'bg-slate-50'}><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Level</th><th className="px-4 py-3">Type</th></tr></thead><tbody className={dark ? 'divide-y divide-slate-700' : 'divide-y divide-slate-200'}>{country.adminLevels.map(area => <tr key={area.id}><td className="px-4 py-3 font-medium">{area.name}</td><td className="px-4 py-3 text-slate-500">{area.level}</td><td className="px-4 py-3 text-slate-500">{levels.find(item => item.level === area.level)?.name || `Level ${area.level}`}</td></tr>)}</tbody></table> : <p className="p-8 text-center text-xs text-slate-500">No administrative areas have been added.</p>}</div></section></div>
    </div>
  </div>;
};
export default CountryProfilePage;
