import React, { useState } from 'react';
import type { ActiveView, CallRecord, CameraDevice, Country, DeletedCallRecord, IDVerificationRequest, Notification, ProductDefinition, RegionalEconomicLevel, Role, Shop, ShopUser, StockItem, Theme, User } from '../types.ts';
import { mockCallRecords, mockCameraDevices, mockNotifications, mockProductDefinitions, mockShopRoles, mockShops, mockShopUsers, mockStockListings, mockSuperUserRoles, mockSuperUsers, mockVerificationRequests } from '../data.ts';
import AdminLoyaltyMgtPage from './AdminLoyaltyMgtPage.tsx';
import ApiSettingsPage from './ApiSettingsPage.tsx';
import BalanceSheetDetailPage from './BalanceSheetDetailPage.tsx';
import BalanceSheetPage from './BalanceSheetPage.tsx';
import CallSettingsPage from './CallSettingsPage.tsx';
import CameraSettingsPage from './CameraSettingsPage.tsx';
import CashFlowDetailPage from './CashFlowDetailPage.tsx';
import CashFlowPage from './CashFlowPage.tsx';
import ClientLoyaltyPage from './ClientLoyaltyPage.tsx';
import ClientsPage from './ClientsPage.tsx';
import ClientWalletsPage from './ClientWalletsPage.tsx';
import CustomerDashboard from './CustomerDashboard.tsx';
import CustomerLoyaltyPage from './CustomerLoyaltyPage.tsx';
import CustomerMakeOrderPage from './CustomerMakeOrderPage.tsx';
import CustomerPurchasesPage from './CustomerPurchasesPage.tsx';
import DailySalesPage from './DailySalesPage.tsx';
import Dashboard from './Dashboard.tsx';
import DistributorsPage from './DistributorsPage.tsx';
import ExchangeRatePage from './ExchangeRatePage.tsx';
import IDVerificationPage from './IDVerificationPage.tsx';
import IncomeStatementDetailPage from './IncomeStatementDetailPage.tsx';
import IncomeStatementPage from './IncomeStatementPage.tsx';
import InventoryPage from './InventoryPage.tsx';
import LeadsPage from './LeadsPage.tsx';
import LookupValuesPage from './LookupValuesPage.tsx';
import ManufacturersPage from './ManufacturersPage.tsx';
import MessageSettingsPage from './MessageSettingsPage.tsx';
import MessagesPage from './MessagesPage.tsx';
import MNOWalletSettingsPage from './MNOWalletSettingsPage.tsx';
import MNOWalletTransactionsPage from './MNOWalletTransactionsPage.tsx';
import MobiAgentSettingsPage from './MobiAgentSettingsPage.tsx';
import PacketTracerConfigPage from './PacketTracerConfigPage.tsx';
import PacketTracerLivePage from './PacketTracerLivePage.tsx';
import PacketTracerPage from './PacketTracerPage.tsx';
import PermissionsPage from './PermissionsPage.tsx';
import ProductDashboard from './ProductDashboard.tsx';
import ProductProfilePage from './ProductProfilePage.tsx';
import ProductsPage from './ProductsPage.tsx';
import ProfilePage from './ProfilePage.tsx';
import ReportsCallsPage from './ReportsCallsPage.tsx';
import RolesPage from './RolesPage.tsx';
import SalesDesk from './SalesDesk.tsx';
import SettingsPage from './SettingsPage.tsx';
import ShopProfilePage from './ShopProfilePage.tsx';
import ShopSurveillancePage from './ShopSurveillancePage.tsx';
import ShopsPage from './ShopsPage.tsx';
import ShopUsersPage from './ShopUsersPage.tsx';
import StockLevelPage from './StockLevelPage.tsx';
import StockListingPage from './StockListingPage.tsx';
import StockPurchasePage from './StockPurchasePage.tsx';
import SuperUsersPage from './SuperUsersPage.tsx';
import SuppliersPage from './SuppliersPage.tsx';
import SystemUsageDashboard from './SystemUsageDashboard.tsx';
import TrafficDashboard from './TrafficDashboard.tsx';
import WalletSettingsPage from './WalletSettingsPage.tsx';

interface Props {
  activeView: ActiveView; theme: Theme; user: User; countries: Country[]; regionalLevels: RegionalEconomicLevel[];
  onNavigate: (view: ActiveView) => void; onUpdateCountry: (country: Country) => Promise<void>;
}

const LegacyFeatureRouter: React.FC<Props> = ({ activeView, theme, user, countries, regionalLevels, onNavigate, onUpdateCountry }) => {
  const [verificationRequests, setVerificationRequests] = useState<IDVerificationRequest[]>(mockVerificationRequests);
  const [shopRoles, setShopRoles] = useState<Role[]>(mockShopRoles);
  const [superUserRoles, setSuperUserRoles] = useState<Role[]>(mockSuperUserRoles);
  const [shopUsers, setShopUsers] = useState<ShopUser[]>(mockShopUsers);
  const [shops, setShops] = useState<Shop[]>(mockShops);
  const [selectedShop, setSelectedShop] = useState<Shop | null>(null);
  const [notifications, setNotifications] = useState<Notification[]>(mockNotifications);
  const [cameraDevices, setCameraDevices] = useState<CameraDevice[]>(mockCameraDevices);
  const [trackedKeywords, setTrackedKeywords] = useState<string[]>([]);
  const [callRecords, setCallRecords] = useState<CallRecord[]>(mockCallRecords);
  const [deletedCallRecords, setDeletedCallRecords] = useState<DeletedCallRecord[]>([]);
  const [products, setProducts] = useState<ProductDefinition[]>(mockProductDefinitions);
  const [stockItems, setStockItems] = useState<StockItem[]>(mockStockListings);
  const [allowCalls, setAllowCalls] = useState(true);
  const [allowMicrophone, setAllowMicrophone] = useState(true);
  const [profileUser, setProfileUser] = useState(user);
  const allUsers = [...shopUsers, ...mockSuperUsers];
  const selectShop = (shop: Shop, view: ActiveView) => { setSelectedShop(shop); onNavigate(view); };
  const addCallRecord = (record: Omit<CallRecord, 'id'>) => setCallRecords(current => [{ ...record, id: `call-${Date.now()}` }, ...current]);
  const deleteCall = (callId: string, reason: string, deletedBy: string) => { const call = callRecords.find(item => item.id === callId); if (!call) return; setCallRecords(current => current.filter(item => item.id !== callId)); setDeletedCallRecords(current => [...current, { ...call, deletedAt: new Date().toISOString(), deletedBy, deletionReason: reason }]); };

  switch (activeView) {
    case 'profile': return <ProfilePage theme={theme} user={profileUser} setUser={setProfileUser} />;
    case 'dashboard': case 'dashboard-users': return <Dashboard theme={theme} shopRoles={shopRoles} superUserRoles={superUserRoles} shopUsers={shopUsers} superUsers={mockSuperUsers} notifications={notifications} onNavigate={onNavigate} trackedKeywords={trackedKeywords} userRole={user.role} regionalLevels={regionalLevels} />;
    case 'dashboard-system': return <SystemUsageDashboard theme={theme} />;
    case 'dashboard-traffic': return <TrafficDashboard theme={theme} regionalLevels={regionalLevels} />;
    case 'dashboard-products': return <ProductDashboard theme={theme} />;
    case 'settings': return <SettingsPage theme={theme} />;
    case 'settings-cameras': return <CameraSettingsPage theme={theme} cameraDevices={cameraDevices} setCameraDevices={setCameraDevices} shops={shops} users={allUsers} currentUser={user} />;
    case 'settings-api': return <ApiSettingsPage theme={theme} currentUser={user} />;
    case 'settings-calls': return <CallSettingsPage theme={theme} allowCalls={allowCalls} setAllowCalls={setAllowCalls} allowMicrophone={allowMicrophone} setAllowMicrophone={setAllowMicrophone} currentUser={user} />;
    case 'id-verification': return <IDVerificationPage theme={theme} requests={verificationRequests} setRequests={setVerificationRequests} />;
    case 'stock-listing': return <StockListingPage theme={theme} currentUser={user} shops={shops} users={shopUsers} stockItems={stockItems} setStockItems={setStockItems} products={products} setProducts={setProducts} />;
    case 'inventory': return <InventoryPage theme={theme} stockItems={stockItems} />;
    case 'stock-purchase': return <StockPurchasePage theme={theme} currentUser={user} products={products} />;
    case 'shop-users': return <ShopUsersPage theme={theme} shopRoles={shopRoles} setVerificationRequests={setVerificationRequests} shopUsers={shopUsers} setShopUsers={setShopUsers} currentUser={user} />;
    case 'super-users': return <SuperUsersPage theme={theme} />;
    case 'permissions': return <PermissionsPage theme={theme} shopRoles={shopRoles} superUserRoles={superUserRoles} setShopRoles={setShopRoles} setSuperUserRoles={setSuperUserRoles} />;
    case 'roles': return <RolesPage theme={theme} shopRoles={shopRoles} superUserRoles={superUserRoles} setShopRoles={setShopRoles} setSuperUserRoles={setSuperUserRoles} shopUsers={shopUsers} setShopUsers={setShopUsers} />;
    case 'shops': return <ShopsPage theme={theme} shops={shops} setShops={setShops} onSelectShop={shop => selectShop(shop, 'shop-profile')} onViewStatement={shop => selectShop(shop, 'income-statement-detail')} countries={countries} users={allUsers} />;
    case 'shop-profile': return <ShopProfilePage theme={theme} shop={selectedShop} users={allUsers} onNavigate={onNavigate} userRole={user.role} currentUserId={user.id} />;
    case 'shop-surveillance': return <ShopSurveillancePage theme={theme} cameraDevices={cameraDevices} />;
    case 'wallet-settings': return <WalletSettingsPage theme={theme} shops={shops} setShops={setShops} />;
    case 'leads': return <LeadsPage theme={theme} users={allUsers} />;
    case 'finances-income-statement': return <IncomeStatementPage theme={theme} onViewStatement={shop => selectShop(shop, 'income-statement-detail')} />;
    case 'finances-balance-sheet': return <BalanceSheetPage theme={theme} onSelectShop={shop => selectShop(shop, 'balance-sheet-detail')} />;
    case 'finances-cash-flow': return <CashFlowPage theme={theme} onSelectShop={shop => selectShop(shop, 'cash-flow-detail')} />;
    case 'income-statement-detail': return <IncomeStatementDetailPage theme={theme} shop={selectedShop} onNavigate={onNavigate} />;
    case 'balance-sheet-detail': return <BalanceSheetDetailPage theme={theme} shop={selectedShop} onNavigate={onNavigate} />;
    case 'cash-flow-detail': return selectedShop ? <CashFlowDetailPage shop={selectedShop} onBack={() => onNavigate('finances-cash-flow')} /> : null;
    case 'reports-messages': return <MessagesPage theme={theme} currentUser={user} users={allUsers} shops={shops} countries={countries} trackedKeywords={trackedKeywords} />;
    case 'reports-calls': return <ReportsCallsPage theme={theme} callRecords={callRecords} deletedCallRecords={deletedCallRecords} onDeleteCall={deleteCall} addCallRecord={addCallRecord} currentUser={user} />;
    case 'reports-daily-sales': return <DailySalesPage theme={theme} />;
    case 'reports-stock-level': return <StockLevelPage theme={theme} />;
    case 'reports-product-profile': return <ProductProfilePage theme={theme} />;
    case 'reports-packet-tracer': return <PacketTracerPage theme={theme} />;
    case 'reports-packet-tracer-live': return <PacketTracerLivePage theme={theme} />;
    case 'reports-packet-tracer-config': return <PacketTracerConfigPage theme={theme} />;
    case 'client-list': return <ClientsPage theme={theme} currentUser={user} addCallRecord={addCallRecord} />;
    case 'client-wallets': return <ClientWalletsPage theme={theme} shops={shops} currentUser={user} />;
    case 'client-loyalty': return <ClientLoyaltyPage theme={theme} />;
    case 'admin-loyalty-mgt': return <AdminLoyaltyMgtPage theme={theme} />;
    case 'system-message-settings': return <MessageSettingsPage theme={theme} users={mockSuperUsers} shops={shops} countries={countries} trackedKeywords={trackedKeywords} setTrackedKeywords={setTrackedKeywords} />;
    case 'product-chain-products': return <ProductsPage theme={theme} onNavigate={onNavigate} products={products} setProducts={setProducts} />;
    case 'product-chain-manufacturers': return <ManufacturersPage theme={theme} currentUser={user} />;
    case 'product-chain-distributors': return <DistributorsPage theme={theme} currentUser={user} />;
    case 'product-chain-suppliers': return <SuppliersPage theme={theme} currentUser={user} shops={shops} />;
    case 'dashboard-customer': return <CustomerDashboard theme={theme} onNavigate={onNavigate} countries={countries} />;
    case 'customer-purchases': return <CustomerPurchasesPage theme={theme} />;
    case 'customer-make-order': return <CustomerMakeOrderPage theme={theme} currentUser={user} countries={countries} />;
    case 'customer-loyalty': return <CustomerLoyaltyPage theme={theme} />;
    case 'sales-desk': return <SalesDesk theme={theme} currentUser={user} onViewSalesHistory={() => onNavigate('reports-daily-sales')} onNavigate={onNavigate} />;
    case 'mobi-agent-settings': return <MobiAgentSettingsPage theme={theme} />;
    case 'mno-wallet-settings': return <MNOWalletSettingsPage theme={theme} />;
    case 'mno-wallet-transactions': return <MNOWalletTransactionsPage theme={theme} />;
    case 'exchange-rate': return <ExchangeRatePage theme={theme} countries={countries} onUpdateCountry={onUpdateCountry} />;
    case 'lookup-values': return <LookupValuesPage theme={theme} />;
    default: return null;
  }
};

export default LegacyFeatureRouter;
