import React, { useEffect, useState } from 'react';
import type { ActiveView, Country, Theme } from '../types.ts';
import type { UgandaElectoralSummary } from '../electoral/types.ts';
import Icon, { type IconName } from './Icon.tsx';

const RegistryOverview: React.FC<{ theme: Theme; countries: Country[]; onNavigate: (view: ActiveView) => void }> = ({ theme, countries, onNavigate }) => {
  const [summary, setSummary] = useState<UgandaElectoralSummary | null>(null);
  const dark = theme === 'dark';
  useEffect(() => { fetch('/api/electoral/uganda/summary').then(r => r.ok ? r.json() : null).then(setSummary).catch(() => undefined); }, []);
  const totalAdminLevels = countries.reduce((sum, country) => sum + (country.numberOfAdminLevels ?? 0), 0);
  const metrics: Array<[string, string, string, IconName]> = [['Countries', countries.length.toLocaleString(), 'Active master records', 'globe'], ['Admin schemas', totalAdminLevels.toLocaleString(), 'Configured hierarchy levels', 'map'], ['Uganda locations', (summary?.normalizedTotals.villagesAndCells ?? 0).toLocaleString(), 'Normalized village/cell records', 'shield-check'], ['Review queue', (summary?.normalizedTotals.recordsNeedingVerification ?? 0).toLocaleString(), 'Records needing attention', 'exclamation-triangle']];
  const card = dark ? 'border-slate-800 bg-slate-900/75' : 'border-slate-200 bg-white';
  return <div className="space-y-6">
    <section className={`relative overflow-hidden rounded-[28px] border px-6 py-8 md:px-9 md:py-10 ${dark ? 'border-emerald-900/40 bg-[#0b1718]' : 'border-emerald-100 bg-[#ecfdf5]'}`}><div className="absolute -right-24 -top-32 h-80 w-80 rounded-full bg-emerald-400/10 blur-3xl" /><div className="relative max-w-3xl"><span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[11px] font-bold uppercase tracking-widest ${dark ? 'border-emerald-800 text-emerald-300' : 'border-emerald-200 bg-white/70 text-emerald-800'}`}><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" /> Registry operational</span><h2 className={`mt-5 text-3xl font-bold tracking-[-0.035em] md:text-4xl ${dark ? 'text-white' : 'text-slate-950'}`}>One trusted structure for every location.</h2><p className={`mt-3 max-w-2xl text-sm leading-6 md:text-[15px] ${dark ? 'text-slate-400' : 'text-slate-600'}`}>Manage territorial definitions, trace electoral locations to their parents, and surface data-quality risks before records reach operational systems.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => onNavigate('country-electoral-levels')} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold text-emerald-950 shadow-lg shadow-emerald-500/20 hover:bg-emerald-400">Explore Uganda registry</button><button onClick={() => onNavigate('countries')} className={`rounded-xl border px-4 py-2.5 text-sm font-semibold ${dark ? 'border-slate-700 bg-slate-900 text-slate-200' : 'border-emerald-200 bg-white text-slate-700'}`}>Manage countries</button></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, hint, icon]) => <article key={label} className={`rounded-2xl border p-5 shadow-sm ${card}`}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold tracking-tight ${dark ? 'text-white' : 'text-slate-950'}`}>{value}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${dark ? 'bg-slate-800 text-emerald-300' : 'bg-emerald-50 text-emerald-700'}`}><Icon name={icon} className="h-5 w-5" /></span></div><p className={`mt-3 text-[11px] ${dark ? 'text-slate-600' : 'text-slate-400'}`}>{hint}</p></article>)}</section>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className={`rounded-2xl border p-5 md:p-6 ${card}`}><h3 className="text-base font-bold">Registry workflow</h3><p className={`mt-1 text-xs ${dark ? 'text-slate-500' : 'text-slate-500'}`}>A controlled path from definition to operational use.</p><div className="mt-6 grid gap-3 md:grid-cols-3">{[['01', 'Define', 'Create country and hierarchy terminology.'], ['02', 'Validate', 'Resolve conflicts and review source provenance.'], ['03', 'Publish', 'Expose stable records to connected services.']].map(([number, title, copy]) => <div key={number} className={`rounded-xl border p-4 ${dark ? 'border-slate-800 bg-slate-950/40' : 'border-slate-100 bg-slate-50'}`}><span className="text-[10px] font-black tracking-widest text-emerald-500">{number}</span><h4 className="mt-3 text-sm font-bold">{title}</h4><p className={`mt-1 text-xs leading-5 ${dark ? 'text-slate-500' : 'text-slate-500'}`}>{copy}</p></div>)}</div></section><section className={`rounded-2xl border p-5 md:p-6 ${card}`}><h3 className="text-base font-bold">Data posture</h3><div className="mt-5 space-y-4">{[['Server-side source', true], ['Stable composite IDs', true], ['Current EC verification', false]].map(([label, good]) => <div key={String(label)} className="flex items-center justify-between text-xs"><span className={dark ? 'text-slate-400' : 'text-slate-600'}>{label}</span><span className={`rounded-full px-2 py-1 font-bold ${good ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-900'}`}>{good ? 'Ready' : 'Required'}</span></div>)}</div></section></div>
  </div>;
};

export default RegistryOverview;
