create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null default '',
  avatar_url text,
  role text not null default 'viewer' check (role in ('admin', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.countries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  country_code text not null unique check (country_code ~ '^[A-Z]{2}$'),
  continent text not null default 'Africa',
  economic_zones text[] not null default '{}',
  currency text not null,
  currency_symbol text not null,
  currency_code text not null check (currency_code ~ '^[A-Z]{3}$'),
  phone_code text not null,
  vat numeric(6,3) not null default 0 check (vat between 0 and 100),
  number_of_admin_levels smallint check (number_of_admin_levels between 0 and 20),
  number_of_electoral_levels smallint check (number_of_electoral_levels between 0 and 20),
  number_of_economic_levels smallint check (number_of_economic_levels between 0 and 20),
  admin_levels jsonb not null default '[]',
  admin_level_names jsonb not null default '[]',
  electoral_level_names jsonb not null default '[]',
  currency_denominators jsonb not null default '[]',
  loyalty_program jsonb,
  rounding_config jsonb,
  sms_local_rate numeric(12,4),
  decimal_places smallint check (decimal_places between 0 and 6),
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.regional_economic_levels (
  id bigint primary key,
  name text not null check (char_length(name) between 1 and 160),
  abbreviation text not null unique check (char_length(abbreviation) between 1 and 20),
  flag text not null default '',
  description text not null default '',
  countries text[] not null default '{}',
  color text not null default '#10b981',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.electoral_datasets (
  id uuid primary key default gen_random_uuid(),
  country_code text not null check (country_code ~ '^[A-Z]{2}$'),
  reference_year smallint not null check (reference_year between 1900 and 2200),
  title text not null,
  status text not null check (status in ('importing', 'historical-needs-verification', 'verified', 'archived', 'failed')),
  source_file text not null,
  authoritative_for_current_use boolean not null default false,
  active boolean not null default false,
  summary jsonb not null default '{}',
  warnings jsonb not null default '[]',
  imported_at timestamptz not null default now(),
  imported_by uuid references auth.users(id) on delete set null
);

create unique index electoral_datasets_one_active_country on public.electoral_datasets(country_code) where active;

create table public.electoral_locations (
  dataset_id uuid not null references public.electoral_datasets(id) on delete cascade,
  id text not null,
  country_code text not null default 'UG' check (country_code ~ '^[A-Z]{2}$'),
  district text not null,
  constituency text not null,
  subcounty text not null,
  parish text not null,
  village text not null,
  search_document tsvector generated always as (
    to_tsvector('simple', village || ' ' || parish || ' ' || subcounty || ' ' || constituency || ' ' || district)
  ) stored,
  needs_verification boolean not null default false,
  sources text[] not null default '{}',
  created_at timestamptz not null default now(),
  primary key (dataset_id, id)
);

create index electoral_locations_district_idx on public.electoral_locations(dataset_id, district);
create index electoral_locations_constituency_idx on public.electoral_locations(dataset_id, district, constituency);
create index electoral_locations_subcounty_idx on public.electoral_locations(dataset_id, district, constituency, subcounty);
create index electoral_locations_parish_idx on public.electoral_locations(dataset_id, district, constituency, subcounty, parish);
create index electoral_locations_search_idx on public.electoral_locations using gin (search_document);

create table public.audit_log (
  id bigint generated always as identity primary key,
  table_name text not null,
  record_id text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  actor_id uuid,
  old_data jsonb,
  new_data jsonb,
  occurred_at timestamptz not null default now()
);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger countries_updated_at before update on public.countries for each row execute function public.set_updated_at();
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger regional_levels_updated_at before update on public.regional_economic_levels for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, email, display_name, avatar_url)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'full_name', new.email, ''), new.raw_user_meta_data ->> 'avatar_url')
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_registry_admin() returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where id = (select auth.uid()) and role = 'admin');
$$;

create or replace function public.protect_profile_identity() returns trigger language plpgsql set search_path = '' as $$
begin
  if not public.is_registry_admin() then
    new.role = old.role;
    new.email = old.email;
  end if;
  return new;
end;
$$;
create trigger profiles_protect_identity before update on public.profiles for each row execute function public.protect_profile_identity();

create or replace function public.write_audit_log() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.audit_log(table_name, record_id, operation, actor_id, old_data, new_data)
  values (tg_table_name, coalesce((to_jsonb(new) ->> 'id'), (to_jsonb(old) ->> 'id')), tg_op, (select auth.uid()), case when tg_op = 'INSERT' then null else to_jsonb(old) end, case when tg_op = 'DELETE' then null else to_jsonb(new) end);
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create trigger countries_audit after insert or update or delete on public.countries for each row execute function public.write_audit_log();
create trigger regional_levels_audit after insert or update or delete on public.regional_economic_levels for each row execute function public.write_audit_log();
create trigger datasets_audit after insert or update or delete on public.electoral_datasets for each row execute function public.write_audit_log();

create or replace function public.activate_electoral_dataset(p_dataset_id uuid) returns void language plpgsql security definer set search_path = '' as $$
declare target_country text;
begin
  select country_code into target_country from public.electoral_datasets where id = p_dataset_id;
  if target_country is null then raise exception 'Dataset not found'; end if;
  update public.electoral_datasets set active = false, status = case when status = 'importing' then 'failed' else 'archived' end where country_code = target_country and active;
  update public.electoral_datasets set active = true where id = p_dataset_id;
end;
$$;

create or replace function public.electoral_options(p_level text, p_district text default null, p_constituency text default null, p_subcounty text default null)
returns table(id text, name text, record_count bigint, needs_verification boolean)
language sql stable security invoker set search_path = '' as $$
  with active_locations as (
    select l.* from public.electoral_locations l join public.electoral_datasets d on d.id = l.dataset_id
    where d.active and l.country_code = 'UG'
      and (p_district is null or l.district = upper(trim(p_district)))
      and (p_constituency is null or l.constituency = upper(trim(p_constituency)))
      and (p_subcounty is null or l.subcounty = upper(trim(p_subcounty)))
  ), options as (
    select case p_level when 'district' then district when 'constituency' then constituency when 'subcounty' then subcounty when 'parish' then parish end as option_name,
      bool_or(active_locations.needs_verification) as verification, count(*) as records
    from active_locations
    group by case p_level when 'district' then district when 'constituency' then constituency when 'subcounty' then subcounty when 'parish' then parish end
  )
  select lower(regexp_replace(option_name, '[^a-zA-Z0-9]+', '-', 'g')), option_name, records, verification from options where option_name is not null order by option_name;
$$;

alter table public.profiles enable row level security;
alter table public.countries enable row level security;
alter table public.regional_economic_levels enable row level security;
alter table public.electoral_datasets enable row level security;
alter table public.electoral_locations enable row level security;
alter table public.audit_log enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant select on public.profiles, public.countries, public.regional_economic_levels, public.electoral_datasets, public.electoral_locations to authenticated;
grant update(display_name, avatar_url) on public.profiles to authenticated;
grant insert, update, delete on public.countries, public.regional_economic_levels to authenticated;
grant select on public.audit_log to authenticated;
grant usage, select on sequence public.countries_id_seq to authenticated;
grant execute on function public.is_registry_admin() to authenticated;
grant execute on function public.electoral_options(text, text, text, text) to authenticated;
revoke execute on function public.activate_electoral_dataset(uuid) from public, anon, authenticated;
grant execute on function public.activate_electoral_dataset(uuid) to service_role;

create policy profiles_read on public.profiles for select to authenticated using (id = (select auth.uid()) or public.is_registry_admin());
create policy profiles_update on public.profiles for update to authenticated using (id = (select auth.uid()) or public.is_registry_admin()) with check (id = (select auth.uid()) or public.is_registry_admin());
create policy countries_read on public.countries for select to authenticated using (true);
create policy countries_write on public.countries for all to authenticated using (public.is_registry_admin()) with check (public.is_registry_admin());
create policy regions_read on public.regional_economic_levels for select to authenticated using (true);
create policy regions_write on public.regional_economic_levels for all to authenticated using (public.is_registry_admin()) with check (public.is_registry_admin());
create policy datasets_read on public.electoral_datasets for select to authenticated using (active);
create policy locations_read on public.electoral_locations for select to authenticated using (exists(select 1 from public.electoral_datasets d where d.id = dataset_id and d.active));
create policy audit_admin_read on public.audit_log for select to authenticated using (public.is_registry_admin());
